### ISSUE TITLE
Issues found when using the package with Opencv DSIFT keypoints

### ISSUE THREAD

**Issue by y-sheng** [ducha-aiki/extract_patches#2]
Hi I attempted to use this package to extract image patches based on OpenCV DSIFT keypoints but the output patches only contain coloured keypoints instead the original images. Please find my notebook pdf and the output as below. 
What I have done was only replacing the ORB detect function to DSIFT.  Any advice would be appreciated.  

[test-extract_patches.pdf](https://github.com/ducha-aiki/extract_patches/files/5465777/test-extract_patches.pdf)

**Comment by ducha-aiki** [comment]
Hi,

Have you tried to extract directly without any drawing? It looks like you have overdrawn keypoints.

**Comment by y-sheng** [comment]
Many thanks!
That solved my issue here. It was weird as I have put different names... but anyway thanks 😄
